### PR TITLE
Tags reordering issue

### PR DESCRIPTION
**Pull request by sdamaraju**

### CODE REVIEW

**Comment by sdamaraju** [comment]
#236 is taken care as part of this Pull request.

**Comment by jessicagood** [comment]
@sdamaraju Did you look at just sorting it in the FlatList on display instead of modifying the object?


    const renderSpotTagsList = () => {
      const tagsCopy = JSON.parse(JSON.stringify(tags));
      return (
        <FlatList
          keyExtractor={item => item.id.toString()}
          data={tagsCopy.sort((tagA, tagB) => tagA.name.localeCompare(tagB.name))}  // alphabetize by name
          renderItem={({item}) => renderTagItem(item)}
          ItemSeparatorComponent={FlatListItemSeparator}
        />
      );
    };

**Comment by sdamaraju** [comment]
@jessicagood  Isn't running the sort on every display call costlier than running the sort occasionally on update of the tags ?

I feel, 
Sorts after the first tag update might not be as costly as the first one as well, as most of the list is already sorted.
On the other hand, display will always run a whole sort, because the list is never in sorted order.

Please suggest.

**Comment by NathanNovak** [comment]
Hey @sdamaraju I talked with @jessicagood and am going to pull this in.

**Pull request merged**
